### ISSUE TITLE
Add new ways to calculate distances and other properties of atoms in clusters

### ISSUE THREAD

**Issue by tjjarvinen** [tjjarvinen/PotentialCalculation.jl#5]
As title says. Thise are need for fitting complex potentials ( https://github.com/tjjarvinen/PotentialFitting.jl )

### TODO
- [x] Distance between two atom in different clusters via index and unitrange
- [x] Angle between atoms in same cluster
- [x] Angle between two atoms in cluster and external point
- [x] Dihedralangle
